name: Build & Release
on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Make zip (SUBFOLDER → berrywalk-feedback)
        env:
          PLUGIN_SLUG: berrywalk-feedback
        run: |
          set -e
          mkdir -p pkg

          # 하위 폴더 → 패키징용 폴더로 복사
          rsync -a "./${PLUGIN_SLUG}/" "pkg/${PLUGIN_SLUG}/" \
            --delete \
            --exclude ".git" \
            --exclude ".github" \
            --exclude "node_modules" \
            --exclude "*.zip" \
            --exclude ".DS_Store"

          # 구조 검증 (메인 파일 & PUC 포함 확인)
          test -f "pkg/${PLUGIN_SLUG}/${PLUGIN_SLUG}.php"
          test -f "pkg/${PLUGIN_SLUG}/plugin-update-checker/plugin-update-checker.php"

          # ZIP 생성
          cd pkg
          zip -r "${PLUGIN_SLUG}-${GITHUB_REF_NAME}.zip" "${PLUGIN_SLUG}"
          unzip -l "${PLUGIN_SLUG}-${GITHUB_REF_NAME}.zip" | sed -n '1,40p'

      - name: Create
